### ISSUE TITLE
Extend API for partial (filtered) indexes

### ISSUE THREAD

**Issue by fljdin** [cybertec-postgresql/db_migrator#15]
Hi Laurenz,

My current research on porting MSSQL to PostgreSQL with a new db_migrator plugin comes with a new API need.
As Oracle does not provide partial indexes, staging `indexes` and `index_columns` tables lack of a filter information.

Given SQL Server [documentation](https://learn.microsoft.com/en-us/sql/relational-databases/indexes/create-filtered-indexes), a partial index must be handled by db_migrator :

```sql
CREATE NONCLUSTERED INDEX FIBillOfMaterialsWithEndDate
    ON Production.BillOfMaterials (ComponentID, StartDate)
    WHERE EndDate IS NOT NULL ;
```

Seems that only PostgreSQL and SQL Server support this feature, as described by Markus [in this post](https://use-the-index-luke.com/sql/where-clause/partial-and-filtered-indexes)

I will give you a patch proposal in a few time.
Regards

**Comment by laurenz** [comment]
It should be easy to add a `where_clause` column to `indexes`.
That expression should be subjected to the `translate_expression_fun` function.
