### ISSUE TITLE
mssql_migrator new plugin

### ISSUE THREAD

**Issue by fljdin** [cybertec-postgresql/db_migrator#17]
Hi,

I released another plugin for SQL Server (https://github.com/fljdin/mssql_migrator) under PostgreSQL license.
Without doing it on purpose, it comes the same week of Ora2Pg v24 release!

Current version 0.0.1 does minimal migration of the AdventureWorks database.
It does not currently consider partition schemes and leaves capitals in identifiers.

Best regards
Florent

**Comment by laurenz** [comment]
I have added a link in the README, see 21f41f329addeb1a64f67e5292a9a68163a21b1a.
