### ISSUE TITLE
db_migrate is not migrating database into PostgreSQL

### ISSUE THREAD

**Issue by naveenjul29** [cybertec-postgresql/db_migrator#2]
db_migrate is working fine for some of the schemas like it is creating schema and dumping the data. But for some of the schemas are not migrating into PostgreSQL using db_migrate and also it is not showing any error details like why it it not migrating. It was saying that migration completed successfully but schema itself is not created in PostgreSQL. Can you please help me with the log

**Comment by laurenz** [comment]
What were the exact SQL statements you used to migrate the database?
What is the name of the schema that was not migrated?
You are using ora_migrator as plugin, right? Are you using the latest development version of everything?
