### ISSUE TITLE
Separate indexes from constraints migration

### ISSUE THREAD

**Issue by fljdin** [cybertec-postgresql/db_migrator#24]
The `db_migrate_constraints` method perform much more that its says, i.e. create constraints.

* Creating primary key or unique constraint
* Creating foreign key constraint
* Creating CHECK constraint
* Creating index
* Setting default to tables columns

Therefore, it may be possible to use dedicated methods for each index or each constraint, as done with `materialize_foreign_table` that is called by `db_migrate_tables` to speed-up operation in parallel.

**Comment by laurenz** [comment]
Yes, that is possible, but it would be some effort.
If you think it is worth it, please go ahead.
