### ISSUE TITLE
Implement BULK loading

### ISSUE THREAD

**Issue by fljdin** [cybertec-postgresql/db_migrator#28]
During `materialize_foreign_table` step, data are loaded from foreign table with a `INSERT AS SELECT *`

[Your recent post][1] about `COPY` performance may inspired `db_migrator` (Ora2Pg already does).

[1]: https://www.cybertec-postgresql.com/en/bulk-load-performance-in-postgresql/

**Comment by laurenz** [comment]
Sure, that sounds like a good idea.
I expect the data transfer to be the bottleneck, so this change might not help a lot, but it won't harm either.

**Comment by laurenz** [comment]
Wait a minute &ndash; how do you want to `COPY` from one (foreign) table to another?

**Comment by fljdin** [comment]
You're right, `COPY` is not intended for that. 

When I said Ora2pg does, it does not after a deep search in [Ora2Pg.pm](https://github.com/darold/ora2pg/blob/master/lib/Ora2Pg.pm#L10110). 
Sorry for this random idea.
