### ISSUE TITLE
db_migrate additional option

### ISSUE THREAD

**Issue by kvaikla** [cybertec-postgresql/db_migrator#3]
Hi, 
Is it possible to add option "keep staging schemas" to db_migrate?

**Comment by laurenz** [comment]
That is easy if you don't call `db_migrate`, but the individual functions that are called by it:

- `db_migrate_prepare`
- `db_migrate_mkforeign`
- `db_migrate_tables`
- `db_migrate_views`
- `db_migrate_constraints`

Just don't call `db_migrate_finish`, which deletes the staging schemas.

**Comment by kvaikla** [comment]
yeah, it's options. thnx
