### ISSUE TITLE
Schema name in capital letters

### ISSUE THREAD

**Issue by TimotheeWright** [cybertec-postgresql/db_migrator#5]
Hi laurenz,

I suggest you write explicitly that the schema must be capitalized in the command SELECT oracle_migrate(server => 'myserver', only_schemas => '{MYSCHEMA}');
or in CREATE FOREIGN TABLE ... SERVER myserver OPTIONS (schema 'MYSCHEMA', table 'ACCOUNT');
because it took me and other developers a while to figure out why it didn't work with lowercase names.

Thanks again for your work on this tool.

**Comment by laurenz** [comment]
Good idea; I have added a mention to the ora_migrator README.
The oracle_fdw documentation already mentions this.
