### ISSUE TITLE
mysql_migrator development

### ISSUE THREAD

**Issue by fljdin** [cybertec-postgresql/db_migrator#7]
Hi Laurenz,

I released a new plugin for MySQL ([fljdin/mysql_migrator](https://github.com/fljdin/mysql_migrator)) with minimal implementation of the staging views required by `db_migrator.db_migrate()` methods.

At this time, the migration is reaching the final stages but with minor constraints errors in my development ([issue #1](https://github.com/fljdin/mysql_migrator/issues/1)).

Best regards,
Florent

**Comment by laurenz** [comment]
Great! tell me as soon as you feel I should add it to the documentation.
I might react slowly, since I'm on vacation until Jan 9.

**Comment by fljdin** [comment]
Hello Laurenz and welcome back to work :smile: 

My plugin `mysql_migrator` looks good to me as it does not encounter any obvious bugs.
I'll appreciate a rapid code review and/or documentation enhancement as you could.

Anyway, I need to study on more difference between MySQL and PostgreSQL to release a final version 1.0. As far as I know:

* https://github.com/fljdin/mysql_migrator/issues/3
* https://github.com/fljdin/mysql_migrator/issues/6

Please feel free to add `mysql_migrator` as an available plugin to `db_migrator`!

**Comment by laurenz** [comment]
Thanks! I have added the link to the documentation.
